playbook:
  goal: Reconcile transactional MMR data to produce a final, accurate monthly snapshot of member risk, revenue, and enrollment status.
  steps:
    - step: mmr-identification-and-structure
      label: Understand MMR file structure, identifiers, and time dimensions.
      checks:
        - check: id-member-identifier-mmr
          label: Identify the primary member identifier (e.g., MBI).
        - check: id-time-dimensions
          label: Differentiate the two key time dimensions - the incurred/covered period and the payment/report date.
          description: "An MMR transaction has two dates: the month it applies to (covered period) and the month the transaction was reported (payment date). This is critical for sequencing."
        - check: id-plan-identifiers
          label: Identify plan-level identifiers like PBP (Plan Benefit Package).
          description: "Note that contract numbers are often missing from MMR files and must be joined from a separate membership/eligibility file."

    - step: mmr-transaction-reconciliation
      label: Determine the nature of the member-month transactions to help with reconcilation to final action status
      checks:
        - check: transaction-restatement
          label: Identify whether MMR transactions are restated or distinct across files.
          description: "Restated transactions would have records with the same member, covered month, payment month, plan, and potentially adjustment reason code present in different in different values of the field 'ursa_file_instance_id'. If present, this 'ursa_file_instance_id' should be used as the concept of a 'file' instead of a CMS file id."
          dependencies:
            - id-time-dimensions
        - check: transaction-sequencing
          label: Establish the chronological sequence of transactions for a given member-month.
          description: "Order transactions by payment/report date. For transactions in the same payment month, use adjustment reason codes as a tie-breaker (e.g., reversals happen before positive adjustments)."
          dependencies:
            - id-time-dimensions
            - core-adjustment-reason-code
        - check: transaction-financial-convention
          label: Determine if financial amounts are 'increase-to' (the change/delta) or 'resulting' (the final value).
          description: "Standard CMS MMRs use 'increase-to' convention. Misinterpreting this leads to incorrect financial totals. It will be important to note any financial fields that do not have any negative values present, as those fields would represent resulting standard instead of increase-to standard."
        - check: transaction-coverage-spans
          label: Determine the length of time that transactions cover
          description: "Member transactions will specify a coverage period in addition to the payment date period. If the covered start and end dates for a given transaction span longer than one month of time, this will be necessary to flag so that downstream logic can split these into one month chunks."
          dependencies:
            - id-time-dimensions
            - transaction-sequencing
            - transaction-financial-convention

    - step: mmr-data-element-analysis
      label: Analyze and interpret key MMR data fields.
      checks:
        - check: core-raf-scores
          label: Identify and validate Part C and Part D Risk Adjustment Factor (RAF) scores.
          description: "Be aware of spurious zero or null RAF scores on records for Part D or for retro-disenrolled members. Use payment amounts to determine if a null/zero RAF is legitimate."
        - check: core-payment-amounts
          label: Identify and validate the various payment and revenue fields (e.g., Total MA Payment, Rebates).
        - check: core-adjustment-reason-code
          label: Interpret the Adjustment Reason Code (ARC) to understand the nature of a transaction.
          description: "Codes indicate events like initial payments, mid-year updates, retroactive hospice status, or disenrollment, which are critical for correct processing."
        - check: core-part-c-vs-d-rows
          label: Distinguish between rows pertaining to Part C (medical) versus Part D (pharmacy) benefits.
          description: "A single payment month can have separate rows for Part C and Part D, which must be handled correctly to avoid misinterpreting nulls (e.g., a null Part C RAF on a Part D row)."
        - check: core-hospice-esrd-status
          label: Identify flags for Hospice and End-Stage Renal Disease (ESRD) status.
          description: "These statuses significantly impact payment calculations and risk attribution."