playbook:
  goal: Understand structure, content, identifiers, and data generation process of incoming medical claims data.
  steps:
    - step: Determine primary patient identifier and locate other useful demographic fields.
      checks:
        - check: Identify potential patient identifier fields (e.g., member_id, patient_id, mbi, ssn).
        - check: Assess reliability and population consistency of identifier fields.
        - check: Determine primary source_local_patient_id candidate.
        - check: Note presence and overlap of multiple identifiers (e.g., Member ID and MBI).
        - check: Identify demographic fields (dob, gender, zip, state) and note formats/completeness.
        - check: Determine state code format (FIPS, SSA, Postal).

    - step: Distinguish Institutional vs. Professional claims.
      checks:
        - check: Determine if claim types are in separate source tables.
        - check: Check for an explicit claim_type_code field and its distinct values (e.g., 'I', 'P', 'institutional', 'professional').
          query: |
            select distinct claim_type_code
            from my_claims_table
            limit 20
        - check: Check presence and population of type_of_bill codes (indicative of Institutional).
        - check: Check presence and population of facility_type_code or place_of_service codes (indicative of Professional).
        - check: Verify harmonization between different indicators if multiple exist.
          query_inst_fac_conflict: |
            select count(*) as should_be_zero
            from my_claims_table
            where claim_type_code = 'I' -- Or equivalent institutional code
            and fac_type_code is not null
            and fac_type_code <> ''
          query_prof_tob_conflict: |
            select count(*) as should_be_zero
            from my_claims_table
            where claim_type_code = 'P' -- Or equivalent professional code
            and bill_type_code is not null
            and bill_type_code <> ''
        - check: Decide on the most reliable field(s) to determine claim class.
